# wrangler.toml
name = 'adminx-bot'
main = "src/index.js"
compatibility_date = "2026-08-18"

[vars]
ENVIRONMENT = "production"
 
[[d1_databases]]
binding = "DB"
database_name = "adminx-bot"
database_id = "a1e03897-023c-4893-96ad-0bed07be3fed"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }
